package AplikasiPendataanAmplang;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class UbahData extends javax.swing.JFrame {

    Database db = new Database();

    public UbahData() {
        initComponents();
        db.Koneksi();
        showData();
    }

    private void showData() {
        try {
            String query = "SELECT * FROM tbAmplang";
            db.st = db.conn.createStatement();
            db.rs = db.st.executeQuery(query);

            // Dapatkan metadata kolom
            ResultSetMetaData metaData = db.rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();

            // Tambahkan nama kolom ke model
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                model.addColumn(metaData.getColumnName(columnIndex));
            }

            // Tambahkan data ke model
            while (db.rs.next()) {
                Object[] row = new Object[columnCount];
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    row[columnIndex - 1] = db.rs.getObject(columnIndex);
                }
                model.addRow(row);
            }

            // Set model pada JTable
            jTable1.setModel(model);

            db.rs.close();
            db.st.close();
        } catch (SQLException e) {
            System.out.println("Error saat mengambil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonUbah = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jComboBoxUmur = new javax.swing.JComboBox<>();
        jTextFieldStok = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pendataan Amplang");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Kembali");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Stok");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ikan Tenggiri", "Ikan Gabus", "Ikan Belida", "Kepiting" }));

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Ukuran");
        jLabel5.setToolTipText("");

        jButtonUbah.setBackground(new java.awt.Color(0, 102, 102));
        jButtonUbah.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUbah.setText("Ubah");
        jButtonUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUbahMouseClicked(evt);
            }
        });

        jButtonBatal.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBatal.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBatal.setText("Batal");
        jButtonBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Harga");

        jComboBoxUmur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Hari", "15 Hari", "20 Hari", "25 Hari" }));

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setText("80 Gram");

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setText("100 Gram");

        buttonGroup.add(jRadioButton3);
        jRadioButton3.setText("150 Gram");

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Rasa");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Umur Simpan");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("ID");

        jTextFieldID.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Ubah Data Amplang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldID)
                                            .addComponent(jTextFieldHarga)
                                            .addComponent(jComboBoxUmur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldStok)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonBatal)
                                            .addComponent(jButtonUbah))))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBatal)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();

        MainMenu main = new MainMenu();
        main.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void kosong() {
        // Mengatur ulang nilai combo box
        jComboBox1.setSelectedIndex(0);
        jComboBoxUmur.setSelectedIndex(0);

        // Mengatur ulang nilai teks field
        jTextFieldID.setText("");
        jTextFieldStok.setText("");
        jTextFieldHarga.setText("");

        // Mengatur ulang nilai radio button
        buttonGroup.clearSelection();
    }

    private void updateData(String rasa, String ukuran, int stok, String umur, int harga, int ID) {
        try {
            String query = "UPDATE `tbamplang` SET `Rasa`=?,`Ukuran`=?,`Stok`=?,`Umur Simpan`=?,`Harga`=? WHERE `ID`=?";
            // Mengatur nilai parameter
            try (PreparedStatement statement = db.conn.prepareStatement(query)) {
                // Mengatur nilai parameter
                statement.setString(1, rasa);
                statement.setString(2, ukuran);
                statement.setInt(3, stok);
                statement.setString(4, umur);
                statement.setInt(5, harga);
                statement.setInt(6, ID);

                // Eksekusi pernyataan UPDATE
                int rowsInserted = statement.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Data berhasil diubah!",
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal mengubah data!",
                            "Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            System.out.println("Error saat memasukkan data: " + e.getMessage());
        }
    }

    private void jButtonUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUbahMouseClicked

        String rasa = (String) jComboBox1.getSelectedItem();
        String ukuran = "";
        String stokStr = "";
        String umur = (String) jComboBoxUmur.getSelectedItem();
        String hargaStr = "";
        String IDStr = "";

        try {
            IDStr = jTextFieldID.getText();
            int ID = Integer.parseInt(IDStr);

            try {
                stokStr = jTextFieldStok.getText();
                int stok = Integer.parseInt(stokStr);

                try {
                    hargaStr = jTextFieldHarga.getText();
                    int harga = Integer.parseInt(hargaStr);

                    boolean isValidSelection = false;
                    if (jRadioButton1.isSelected()) {
                        ukuran = "80 Gram";
                        isValidSelection = true;
                    } else if (jRadioButton2.isSelected()) {
                        ukuran = "100 Gram";
                        isValidSelection = true;
                    } else if (jRadioButton3.isSelected()) {
                        ukuran = "150 Gram";
                        isValidSelection = true;
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Ukuran tidak valid, pilih ukuran!",
                                "Gagal", JOptionPane.ERROR_MESSAGE);
                    }

                    if (isValidSelection) {
                        // Lakukan update data
                        updateData(rasa, ukuran, stok, umur, harga, ID);
                        showData();
                        kosong();
                    }
                } catch (NumberFormatException e) {
                    // Penanganan ketika teks tidak dapat diubah menjadi integer
                    JOptionPane.showMessageDialog(this,
                            "Harga tidak valid, masukkan angka!",
                            "Gagal", JOptionPane.ERROR_MESSAGE);
                    jTextFieldHarga.setText("");
                }
            } catch (NumberFormatException e) {
                // Penanganan ketika teks tidak dapat diubah menjadi integer
                JOptionPane.showMessageDialog(this,
                        "Stok tidak valid, masukkan angka!",
                        "Gagal", JOptionPane.ERROR_MESSAGE);
                jTextFieldStok.setText("");
            }
        } catch (NumberFormatException e) {
            // Penanganan ketika teks tidak dapat diubah menjadi integer
            JOptionPane.showMessageDialog(this,
                    "ID tidak valid, pilih data yang ada pada tabel!",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUbahMouseClicked

    private void jButtonBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalMouseClicked
        kosong();
    }//GEN-LAST:event_jButtonBatalMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();

        Object value = jTable1.getValueAt(selectedRow, 0);
        String selectedValue = value.toString();
        jTextFieldID.setText(selectedValue);

        Object value1 = jTable1.getValueAt(selectedRow, 1);
        String selectedValue1 = value1.toString();
        jComboBox1.setSelectedItem(selectedValue1);

        Object value2 = jTable1.getValueAt(selectedRow, 2);
        if (value2.equals("80 Gram")) {
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
        } else if (value2.equals("100 Gram")) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
            jRadioButton3.setSelected(false);
        } else if (value2.equals("150 Gram")) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(true);
        } else {
            // Penanganan jika nilai tidak sesuai
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
        }

        Object value3 = jTable1.getValueAt(selectedRow, 3);
        String selectedValue3 = value3.toString();
        jTextFieldStok.setText(selectedValue3);

        Object value4 = jTable1.getValueAt(selectedRow, 4);
        String selectedValue4 = value4.toString();
        jComboBoxUmur.setSelectedItem(selectedValue4);

        Object value5 = jTable1.getValueAt(selectedRow, 5);
        String selectedValue5 = value5.toString();
        jTextFieldHarga.setText(selectedValue5);
    }//GEN-LAST:event_jTable1MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UbahData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxUmur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldStok;
    // End of variables declaration//GEN-END:variables
}
