package AplikasiAmplang;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TambahData extends javax.swing.JFrame {

    Database db = new Database();

    public TambahData() {
        initComponents();
        db.Koneksi();
        showData();
    }

    private void showData() {
        try {
            String query = "SELECT `Rasa`, `Ukuran`, `Stok`, `Umur Simpan`, `Harga` FROM `tbamplang`";
            db.st = db.conn.createStatement();
            db.rs = db.st.executeQuery(query);

            // Dapatkan metadata kolom
            ResultSetMetaData metaData = db.rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Buat model tabel
            DefaultTableModel model = new DefaultTableModel();

            // Tambahkan nama kolom ke model
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                model.addColumn(metaData.getColumnName(columnIndex));
            }

            // Tambahkan data ke model
            while (db.rs.next()) {
                Object[] row = new Object[columnCount];
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    row[columnIndex - 1] = db.rs.getObject(columnIndex);
                }
                model.addRow(row);
            }

            // Set model pada JTable
            jTable1.setModel(model);

            db.rs.close();
            db.st.close();
        } catch (SQLException e) {
            System.out.println("Error saat mengambil data: " + e.getMessage());
        }
    }

    private void insertData(String rasa, String ukuran, int stok, String umur, int harga) {
        try {
            String query = "INSERT INTO `tbamplang`(`Rasa`, `Ukuran`, `Stok`, `Umur Simpan`, `Harga`) VALUES (?, ?, ?, ?, ?)";
            // Mengatur nilai parameter
            try (PreparedStatement statement = db.conn.prepareStatement(query)) {
                // Mengatur nilai parameter
                statement.setString(1, rasa);
                statement.setString(2, ukuran);
                statement.setInt(3, stok);
                statement.setString(4, umur);
                statement.setInt(5, harga);

                // Eksekusi pernyataan INSERT
                int rowsInserted = statement.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Data berhasil ditambahkan!",
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Gagal menambahkan data!",
                            "Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            System.out.println("Error saat memasukkan data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jComboBoxUmur = new javax.swing.JComboBox<>();
        jTextFieldStok = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonTambah = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Kembali");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Rasa");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Umur Simpan");

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Stok");

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Ukuran");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Harga");

        jComboBoxUmur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Hari", "15 Hari", "20 Hari", "25 Hari" }));

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setText("80 Gram");

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setText("100 Gram");

        buttonGroup.add(jRadioButton3);
        jRadioButton3.setText("150 Gram");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ikan Tenggiri", "Ikan Gabus", "Ikan Belida", "Kepiting" }));

        jButtonTambah.setBackground(new java.awt.Color(0, 102, 102));
        jButtonTambah.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTambah.setText("Tambah");
        jButtonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTambahMouseClicked(evt);
            }
        });

        jButtonBatal.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBatal.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBatal.setText("Batal");
        jButtonBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHarga)
                            .addComponent(jComboBoxUmur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldStok)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1)
                            .addComponent(jComboBox1, 0, 135, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBatal)
                            .addComponent(jButtonTambah))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBatal)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();

        MainMenu main = new MainMenu();
        main.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void updateStok(int Stok, int StokLama, int ID) {
        String query = "UPDATE tbAmplang SET `Stok`=? WHERE `ID` = ?";
        try (PreparedStatement statement = db.conn.prepareStatement(query)) {
            // Mengatur nilai parameter untuk data yang akan diubah
            int StokBaru = Stok + StokLama;
            statement.setInt(1, StokBaru);
            // Mengatur nilai parameter untuk kondisi WHERE
            statement.setInt(2, ID);

            // Eksekusi query UPDATE
            int rowsUpdated = statement.executeUpdate();

            if (rowsUpdated > 0) {
                // Data berhasil diubah
                JOptionPane.showMessageDialog(this,
                        "Data yang dimasukkan sudah ada, maka stok ditambahkan!",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Tidak ada data yang terpenuhi kondisi WHERE, atau tidak ada perubahan data
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error saat menjalankan query: " + e.getMessage(),
                    "Gagal", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void jButtonTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTambahMouseClicked
        String rasa = (String) jComboBox1.getSelectedItem();
        String ukuran = "";
        String stokStr = "";
        String umur = (String) jComboBoxUmur.getSelectedItem();
        String hargaStr = "";

        try {
            hargaStr = jTextFieldHarga.getText();
            int harga = Integer.parseInt(hargaStr);

            try {
                stokStr = jTextFieldStok.getText();
                int stok = Integer.parseInt(stokStr);

                boolean isValidSelection = false;
                if (jRadioButton1.isSelected()) {
                    ukuran = "80 Gram";
                    isValidSelection = true;
                } else if (jRadioButton2.isSelected()) {
                    ukuran = "100 Gram";
                    isValidSelection = true;
                } else if (jRadioButton3.isSelected()) {
                    ukuran = "150 Gram";
                    isValidSelection = true;
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ukuran tidak valid, pilih ukuran!",
                            "Gagal", JOptionPane.ERROR_MESSAGE);
                }

                if (isValidSelection) {
                    String query = "SELECT * FROM tbAmplang WHERE `Rasa` = ? AND `Ukuran` = ? AND `Umur Simpan` = ? AND `Harga` = ?";
                    try (PreparedStatement statement = db.conn.prepareStatement(query)) {
                        // Mengatur nilai parameter
                        statement.setString(1, rasa);
                        statement.setString(2, ukuran);
                        statement.setString(3, umur);
                        statement.setInt(4, harga);

                        // Eksekusi query SELECT
                        ResultSet resultSet = statement.executeQuery();

                        // Memeriksa hasil query
                        if (resultSet.next()) {
                            // Data sudah ada di database
                            String IDStr = resultSet.getString("ID");
                            int ID = Integer.parseInt(IDStr);

                            String StokStr = resultSet.getString("Stok");
                            int Stok = Integer.parseInt(StokStr);

                            updateStok(stok, Stok, ID);
                            showData();
                            kosong();
                        } else {
                            // Data belum ada di database
                            // Lakukan insert data
                            insertData(rasa, ukuran, stok, umur, harga);
                            showData();
                            kosong();
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this,
                                "Error saat menjalankan query: " + e.getMessage(),
                                "Gagal", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (NumberFormatException e) {
                // Penanganan ketika teks tidak dapat diubah menjadi integer
                JOptionPane.showMessageDialog(this,
                        "Stok tidak valid, masukkan angka!",
                        "Gagal", JOptionPane.ERROR_MESSAGE);
                jTextFieldStok.setText("");
            }
        } catch (NumberFormatException e) {
            // Penanganan ketika teks tidak dapat diubah menjadi integer
            JOptionPane.showMessageDialog(this,
                    "Harga tidak valid, masukkan angka!",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            jTextFieldHarga.setText("");
        }
    }//GEN-LAST:event_jButtonTambahMouseClicked

    private void jButtonBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalMouseClicked
        kosong();
    }//GEN-LAST:event_jButtonBatalMouseClicked

    private void kosong() {
        // Mengatur ulang nilai combo box
        jComboBox1.setSelectedIndex(0);
        jComboBoxUmur.setSelectedIndex(0);

        // Mengatur ulang nilai teks field
        jTextFieldStok.setText("");
        jTextFieldHarga.setText("");

        // Mengatur ulang nilai radio button
        buttonGroup.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TambahData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxUmur;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldStok;
    // End of variables declaration//GEN-END:variables
}
